server:
  port: 8003

spring:
  application:
    name: cloud-config8003
  cloud:
    config:
      server:
        git:
          uri: https://github.com/min-sl/spring-cloud-config-repository #git仓库地址
          username:   #账号
          password:    #密码
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: cloud-config-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
