server:
  port: 8002

spring:
  application:
    name: provider8002

eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/ #注册中心的地址
  instance:
    instance-id: payment8002
    prefer-ip-address: true #访问路径显示ip地址