server:
  port: 8003

spring:
  application:
    name: cloud-config8003
  cloud:
    config:
      server:
        git:
          uri: https://github.com/min-sl/spring-cloud-config-repository #git仓库地址
          username: msl1395323284@163.com   #账号
          password: msl19980303    #密码
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: cloud-config-server