server:
  port: 9000

spring:
    application:
      name: consumer9000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: consumer9000
  client:
    register-with-eureka: true #表示向注册中心注册自己
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/ #注册中心的地址
feign:
  hystrix:
    enabled: true #开启hystrix熔断